export const SET_OPERATION_TYPE = 'SET_OPERATION_TYPE';
export const ANSWERED_QUESTION = 'ANSWERED_QUESTION';
export const UPDATE_SCORE = 'UPDATE_SCORE';
export const UPDATE_LIVES = 'UPDATE_LIVES';
export const MODAL_VISIBILITY = 'MODAL_VISIBILITY';
export const MODAL_TYPE = 'MODAL_TYPE';
export const COUNT_AD_MOB_INTERVAL = 'COUNT_AD_MOB_INTERVAL';
